server:
  port: 9822

spring:
  datasource:
    url: jdbc:mysql://192.168.100.8:5509/easycode?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: suncompass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:mapper/*.xml